const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const resources = [
  { id: 1, title: "Advanced Biology Lab Manual", subject: "Biology" },
  { id: 2, title: "Chemistry Formula Handbook", subject: "Chemistry" },
  { id: 3, title: "Physics Problem-Solving Guide", subject: "Physics" },
  { id: 4, title: "Mathematics Cheat Sheet", subject: "Mathematics" },
  { id: 5, title: "Scientific Method Workbook", subject: "General Science" },
  { id: 6, title: "Environmental Science Guide", subject: "Environmental Science" }
];

const outputDir = path.join(__dirname, 'public', 'resources');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

resources.forEach((resource) => {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const filename = path.join(outputDir, `resource-${resource.id}.pdf`);
  const stream = fs.createWriteStream(filename);

  doc.pipe(stream);

  // Title
  doc.fontSize(24).font('Helvetica-Bold').text(resource.title, { align: 'center' });
  doc.moveDown(0.5);

  // Subject
  doc.fontSize(12).font('Helvetica').text(`Subject: ${resource.subject}`, { align: 'center' });
  doc.moveDown(1);

  // Divider
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown(1);

  // Content
  doc.fontSize(14).font('Helvetica-Bold').text('About This Resource', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(11).font('Helvetica').text(
    `This comprehensive resource has been designed for SciVenture students to enhance their learning in ${resource.subject}. ` +
    `It contains carefully curated content, practical examples, and problem-solving strategies.`,
    { align: 'justify' }
  );
  doc.moveDown(1);

  // Features
  doc.fontSize(14).font('Helvetica-Bold').text('Key Features:', { underline: true });
  doc.moveDown(0.5);
  const features = [
    '• Comprehensive coverage of core concepts',
    '• Real-world examples and case studies',
    '• Practice problems with solutions',
    '• Visual diagrams and illustrations',
    '• Quick reference guides'
  ];

  features.forEach(feature => {
    doc.fontSize(11).font('Helvetica').text(feature);
    doc.moveDown(0.3);
  });

  doc.moveDown(1);

  // Learning Objectives
  doc.fontSize(14).font('Helvetica-Bold').text('How to Use This Resource:', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(11).font('Helvetica').text(
    '1. Start with the foundational concepts\n' +
    '2. Work through the practice problems\n' +
    '3. Review the solutions and explanations\n' +
    '4. Use as a reference during your studies\n' +
    '5. Share with classmates and team members',
    { align: 'left' }
  );

  doc.moveDown(2);

  // Footer
  doc.fontSize(9).font('Helvetica').text('Generated by SciVenture - Interactive Science Education Platform', { align: 'center' });
  doc.fontSize(8).text(`Document created on ${new Date().toLocaleDateString()}`, { align: 'center' });

  doc.end();

  stream.on('finish', () => {
    console.log(`✓ Created ${filename}`);
  });
});

console.log('PDF generation started for all resources...');
